alter table STOCK_PURCHASE_ORDER add constraint FK_STOCK_PURCHASE_ORDER_CUSTOMER foreign key (CUSTOMER_ID) references STOCK_CUSTOMER(ID);
create index IDX_STOCK_PURCHASE_ORDER_CUSTOMER on STOCK_PURCHASE_ORDER (CUSTOMER_ID);
