alter table STOCK_PURCHASE_ORDER add constraint FK_STOCK_PURCHASE_ORDER_ITEMS foreign key (ITEMS_ID) references STOCK_ITEM(ID);
create index IDX_STOCK_PURCHASE_ORDER_ITEMS on STOCK_PURCHASE_ORDER (ITEMS_ID);
